apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: templateinstances.template.openshift.io
spec:
  group: template.openshift.io
  names:
    kind: TemplateInstance
    listKind: TemplateInstanceList
    plural: templateinstances
    singular: templateinstance
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              template:
                type: object
              secret:
                type: object
                properties:
                  name:
                    type: string
            required:
              - template
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
                required:
                  - type
                  - status
